services:
  laravel-service:
    build:
      context: ../
      dockerfile: development/laravel-service/Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ../laravel-service:/var/www
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_database
      DB_USERNAME: test
      DB_PASSWORD: test

  native-service:
    build:
      context: ../
      dockerfile: development/native-service/Dockerfile
    ports:
      - "5002:80"
    volumes:
      - ../native-service:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../laravel-service:/var/www
      - ../native-service:/var/www
    depends_on:
      - laravel-service
      - native-service

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: laravel_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: